### ISSUE TITLE
util.multiCall seems to be not working

### ISSUE THREAD

**Issue by ChinHongTan** [Tenpi/pixiv.ts#25]
I'm not very sure if I am using it wrongly, here's my code snippet:
```js
const pixiv = await Pixiv.default.refreshLogin(refreshToken);
const word = 'ロリ';
let illusts = await pixiv.search.illusts({ word: word, r18: false, type:'illust', bookmarks: '1000' });
if (pixiv.search.nextURL) illusts = [...illusts, ...await pixiv.util.multiCall({ next_url: pixiv.search.nextURL, illusts }, 2)];
```
I noticed that no matter what number I use for limit (which is 2 in the code above), it always ends up returning `Error: Request failed with status code 400`. If no limit is provided, it will end up returning `Error: Request failed with status code 403`.

Also, using `await Pixiv.refreshLogin(refreshToken)` like the example in the readme.md will not work. An error will pop up saying `TypeError: Pixiv.refreshLogin is not a function`. It took me quite a while to figure out that I have to use `Pixiv.default.refreshLogin` instead.

**Comment by Tenpi** [comment]
Your refresh token is wrong. Please follow this guide on how to obtain your refresh token: [link](https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362)

I have clearly shown that the imports are with ES6.
```ts
import Pixiv from "pixiv.ts"
```
If you use CommonJS, you need to append `default` because it doesn't support a default export.
```ts
const Pixiv = require("pixiv.ts").default
```

I've also modified `util.multiCall()` to merge the passed results into the array, so the following should be sufficient now:
```ts
let illusts = await pixiv.search.illusts({word: "ロリ"})
if (pixiv.search.nextURL) illusts = await pixiv.util.multiCall({next_url: pixiv.search.nextURL, illusts}, 2)
```
